apiVersion: apps/v1
kind: Deployment
metadata:
  name: rest1-deployment
  namespace: pfinal
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rest1-app
  template:
    metadata:
      labels:
        app: rest1-app
    spec:
      containers:
        - name: rest1-app
          image: crodriguezcarr0611/proyectofinal:rest1-v1
          ports:
            - containerPort: 9095
          envFrom:
            - configMapRef:
                name: rest1-config