apiVersion: v1
kind: Service
metadata:
  name: rest1-service
  namespace: pfinal
spec:
  selector:
    app: rest1-app
  ports:
    - protocol: TCP
      port: 8095
      targetPort: 9095
  type: ClusterIP